version: "3.9"

services:
  be:
    build:
      context: ./be
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./be:/app
      - ~/.m2:/root/.m2
    env_file:
      - ./be/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  spreadsheet:
    build:
      context: ./services/spread-sheet
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./services/spread-sheet:/app
    env_file:
      - ./services/spread-sheet/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./fe/.env
    depends_on:
      - be
      - spreadsheet
