#############################################
# Server Settings
#############################################
spring.application.name=spread-sheet
server.port=${SERVER_PORT}
#############################################
# Frontend
#############################################
frontend.url=${FRONTEND_URL}
#############################################
# Database Configuration
#############################################
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
#############################################
# JWT Security
#############################################
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME}
#############################################
# File Upload
#############################################
spring.servlet.multipart.max-file-size=${MAX_UPLOAD_SIZE}
#############################################
# External Services
#############################################
service.sheet.url=${SERVICE_URL}
