FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

RUN apk add --no-cache maven git bash

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src

EXPOSE 8080

ENV SPRING_DEVTOOLS_RESTART_ENABLED=true
ENV SPRING_DEVTOOLS_LIVE_RELOAD_ENABLED=true

CMD ["mvn", "spring-boot:run"]